# for more info see:
# https://www.jenkins.io/doc/book/installing/docker/#downloading-and-running-jenkins-in-docker

FROM jenkins/jenkins:2.249.3-slim

RUN jenkins-plugin-cli --plugins blueocean:1.24.3
